/**
 * @name autoReplyTagManager
 * @description จัดการระบบตอบกลับอัตโนมัติเมื่อมีคนแท็ก UID (เฉพาะแอดมิน)
 * @version 1.0.0
 * @author Auto Generated by สร้างคำสั่ง
 */

const fs = require('fs');
const path = require('path');

// ไฟล์เก็บการตั้งค่า Auto Reply Tag
const CONFIG_FILE = path.join(__dirname, 'autoReplyTagConfig.json');

// โหลดการตั้งค่า
function loadConfig() {
    try {
        if (fs.existsSync(CONFIG_FILE)) {
            return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
        }
    } catch (error) {
        console.error('[AutoReplyTag Config] Error loading config:', error);
    }
    return {
        enabled: true,
        targetUID: "61555184860915",
        replyMessage: "ไม่ว่าง",
        threads: {} // thread-specific settings
    };
}

// บันทึกการตั้งค่า
function saveConfig(config) {
    try {
        fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
        return true;
    } catch (error) {
        console.error('[AutoReplyTag Config] Error saving config:', error);
        return false;
    }
}

module.exports = {
    name: "autoReplyTagManager",
    description: "จัดการระบบตอบกลับอัตโนมัติเมื่อมีคนแท็ก UID (เฉพาะแอดมิน)",
    version: "1.0.0",
    aliases: ["artm", "autoreply"],
    nashPrefix: false,
    cooldowns: 5,

    async execute(api, event, args, prefix) {
        const { threadID, messageID, senderID } = event;
        const action = args[0]?.toLowerCase();
        const config = loadConfig();

        // ตรวจสอบสิทธิ์แอดมิน
        const adminUID = global.config?.adminUID || "61555184860915";
        if (senderID !== adminUID) {
            return api.sendMessage("❌ คำสั่งนี้ใช้ได้เฉพาะแอดมินเท่านั้น", threadID, messageID);
        }

        try {
            switch (action) {
                case 'on':
                case 'เปิด':
                    config.enabled = true;
                    if (saveConfig(config)) {
                        api.sendMessage("✅ เปิดระบบ Auto Reply Tag แล้ว", threadID, messageID);
                    } else {
                        api.sendMessage("❌ เกิดข้อผิดพลาดในการเปิดระบบ", threadID, messageID);
                    }
                    break;

                case 'off':
                case 'ปิด':
                    config.enabled = false;
                    if (saveConfig(config)) {
                        api.sendMessage("✅ ปิดระบบ Auto Reply Tag แล้ว", threadID, messageID);
                    } else {
                        api.sendMessage("❌ เกิดข้อผิดพลาดในการปิดระบบ", threadID, messageID);
                    }
                    break;

                case 'setmessage':
                case 'ตั้งข้อความ':
                    const newMessage = args.slice(1).join(' ');
                    if (!newMessage) {
                        api.sendMessage("❌ กรุณาระบุข้อความที่ต้องการตั้ง\nตัวอย่าง: autoReplyTagManager ตั้งข้อความ ไม่ว่างนะ", threadID, messageID);
                        break;
                    }
                    config.replyMessage = newMessage;
                    if (saveConfig(config)) {
                        api.sendMessage(`✅ ตั้งข้อความตอบกลับใหม่: "${newMessage}"`, threadID, messageID);
                    } else {
                        api.sendMessage("❌ เกิดข้อผิดพลาดในการตั้งข้อความ", threadID, messageID);
                    }
                    break;

                case 'setuid':
                case 'ตั้งไอดี':
                    const newUID = args[1];
                    if (!newUID) {
                        api.sendMessage("❌ กรุณาระบุ UID ที่ต้องการตั้ง\nตัวอย่าง: autoReplyTagManager ตั้งไอดี 61555184860915", threadID, messageID);
                        break;
                    }
                    config.targetUID = newUID;
                    if (saveConfig(config)) {
                        api.sendMessage(`✅ ตั้ง UID เป้าหมายใหม่: ${newUID}`, threadID, messageID);
                    } else {
                        api.sendMessage("❌ เกิดข้อผิดพลาดในการตั้ง UID", threadID, messageID);
                    }
                    break;

                case 'status':
                case 'สถานะ':
                case undefined:
                    const adminUID = global.config?.adminUID || "61555184860915";
                    const statusMessage = `🤖 สถานะระบบ Auto Reply Tag\n` +
                                        `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
                                        `📊 สถานะ: ${config.enabled ? '🟢 เปิดใช้งาน' : '🔴 ปิดใช้งาน'}\n` +
                                        `🎯 UID เป้าหมาย: ${config.targetUID}\n` +
                                        `💬 ข้อความตอบกลับ: "${config.replyMessage}"\n` +
                                        `👑 แอดมิน: ${adminUID}\n\n` +
                                        `📋 คำสั่งที่ใช้ได้ (เฉพาะแอดมิน):\n` +
                                        `• ${prefix}autoReplyTagManager เปิด - เปิดระบบ\n` +
                                        `• ${prefix}autoReplyTagManager ปิด - ปิดระบบ\n` +
                                        `• ${prefix}autoReplyTagManager ตั้งข้อความ <ข้อความ> - เปลี่ยนข้อความตอบกลับ\n` +
                                        `• ${prefix}autoReplyTagManager ตั้งไอดี <UID> - เปลี่ยน UID เป้าหมาย\n` +
                                        `• ${prefix}autoReplyTagManager สถานะ - ดูสถานะปัจจุบัน`;
                    api.sendMessage(statusMessage, threadID, messageID);
                    break;

                default:
                    api.sendMessage(`❌ คำสั่งไม่ถูกต้อง\nใช้: ${prefix}autoReplyTagManager สถานะ เพื่อดูคำสั่งที่ใช้ได้`, threadID, messageID);
                    break;
            }
        } catch (error) {
            console.error('[AutoReplyTagManager Error]:', error);
            api.sendMessage(`❌ เกิดข้อผิดพลาด: ${error.message}`, threadID, messageID);
        }
    }
};
